name: Heroku OFF

on:
  schedule:
    # Disable Heroku app at 17:00 UTC every day
    - cron: '0 17 * * *'

jobs:
  heroku:
    runs-on: ubuntu-latest
    name: Enable maintenance mode
    steps:
      - name: enable-heroku-app
        run: |
          wget https://raw.githubusercontent.com/wabarc/on-heroku/master/maintenance.sh -O maintenance.sh
          sh maintenance.sh -k ${{ secrets.HEROKU_APIKEY }} -a ${{ secrets.HEROKU_APPNAME }} -m on
