name: Heroku ON

on:
  schedule:
    # Enable Heroku app at 23:59 UTC every day
    - cron: '59 23 * * *'

jobs:
  heroku:
    runs-on: ubuntu-latest
    name: Disable maintenance mode
    steps:
      - name: disable-heroku-app
        run: |
          wget https://raw.githubusercontent.com/wabarc/on-heroku/master/maintenance.sh -O maintenance.sh
          sudo sh maintenance.sh -k ${{ secrets.HEROKU_APIKEY }} -a ${{ secrets.HEROKU_APPNAME }} -m off
